language: php

sudo: required

language: php

services:
  - mysql
  - postgresql
  - docker
  
addons:
  apt:
    packages:
      - g++

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2
 
env:
 global:
  - MOODLE_BRANCH=MOODLE_35_STABLE
  - MOODLE_BRANCH=master

 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

before_script:
  - chmod +x /home/travis/build/moodle/mod/vpl/tests/vpl_evaluate/test_vpl_evaluate.sh

script:
  - moodle-plugin-ci phplint
#  CPD errors I need to rewrite scala and python tokenizer
#  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
  - /home/travis/build/moodle/mod/vpl/tests/vpl_evaluate/test_vpl_evaluate.sh
